Algoritmo "EXERCICIO48"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Use a tag enquanto e fimenquanto
// Autor(a)    : Leandro de Oliveira Custodio
// Data atual  : 01/09/2021
Var
// Seção de Declarações das variáveis 
rato:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto rato<10 faca
escreval("Rato Australiano", rato+1)
rato<-rato+1
fimenquanto
Fimalgoritmo