Algoritmo "Para1"
// Disciplina   : [Lógica de Programação e JavaScript]
// Professor   : Jailson
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Leandro
// Data atual  : 03/09/2021
Var
// Seção de Declarações das variáveis 
cont, numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para cont de 15 ate 200 faca
numero<-cont*cont
escreval("O quadrado de ",cont," é = ",numero)
fimpara

Fimalgoritmo